name: TimerPro
version: '${project.version}'
author: Tinhde061
main: me.qpneruy.timerplugin.TimerPro
api-version: '1.18'
commands:
  Sync_Time:
    description: "Đồng bộ thời gian thật"
  Add_Time:
    description: "Thêm giờ"
    usage: <command> <hh:mm> <mob_id>