name: TimerPro
version: '${project.version}'
author: qpneruy
main: me.qpneruy.timerplugin.TimerPro
api-version: '1.18'
description: Lên Lịch Thực thi cho lệnh
depend: [PlaceholderAPI]

commands:
  themlenh:
    description: "Thêm lệnh vào tim em"
    permission: TimerPro.themlenh
  xoalenh:
    description: "Xóa lệnh đã được thêm."
    permission: TimerPro.xoalenh
  xemlenh:
    description: "Hiện tất cả lệnh đã được thêm."
    permission: TimerPro.xemlenh
  sualenh:
    description: "Thay đổi thông số lệnh."
    permission: TimerPro.sualenh
  timerpro:
    description: "Menu Lệnh."
    permission: TimerPro.timerpro

permissions:
  TimerPro.themlenh:
    description: Quyền sử dụng Themlenh
    default: op
  TimerPro.xemlenh:
    description: Quyền sử dụng lệnh Xemlenh
    default: op
  TimerPro.sualenh:
    description: Quyền sử dụng sualenh
    default: op
  TimerPro.xoalenh:
    description: Quyền sử dụng lệnh Xoalenh
    default: op
  TimerPro.timerpro:
    description: Quyền sử dụng lệnh timerpro
    default: op