name: TimerPro
version: '${project.version}'
author: qpneruy
main: me.qpneruy.timerplugin.TimerPro
api-version: '1.18'
commands:
  taskcancel:
    description: "task start"
    usage: <command>
  StartSave:
    description: "task start"
    usage: <command>
  add_Time:
    description: "add new time"
    usage: <command>